version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: manualmind-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  manualmind:
    build: .
    container_name: manualmind-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - MAX_CHUNK_SIZE=1000
      - CHUNK_OVERLAP=100
      - RATE_LIMIT_PER_MINUTE=10
    env_file:
      - .env
    volumes:
      - ./media:/app/media:ro  # Mount media folder as read-only
      - ./static:/app/static   # Mount static files
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: manualmind-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./static:/var/www/static:ro
    depends_on:
      - manualmind
    profiles:
      - production

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: manualmind-network